Repository Ensembl/ensembl-metadata, pull requests merged in 2019-04, with the labels that each got.

#57 These two scripts are meant to be executable
  misc_scripts/get_list_genomes_for_division.pl
  misc_scripts/report_genomes.pl
Labels: enhancement

#58 Renaming of genomes inside a collection was not reported because the …
  misc_scripts/report_genomes.pl
Labels: bugfix

#59 Fixed a typo which mean that the division-removed_genomes.txt was mis…
  misc_scripts/report_genomes.pl
Labels: bugfix

#60 added optional -strain flag
  misc_scripts/get_list_genomes_for_division.pl
Labels: enhancement

#61 Updating farm queue to use production-rh74 which has more capacity
  .travis.yml
  modules/Bio/EnsEMBL/MetaData/Pipeline/MetadataUpdater_conf.pm
  travisci/harness.sh
Labels: bau
